// Auto-extracted from original index.html — DO NOT hand-edit the data
// ===== 单词数据库 + 图标映射 =====
var CAT_ICONS = {
  'Animals':'🦁','Vehicles':'🚗','Furniture':'🛋️','Food':'🍎',
  'Colors':'🎨','Shapes':'⭐','Clothes':'👕','Home':'🏠',
  'Nature':'🌳','Body':'💪','Numbers':'🔢','Time':'🕐',
  'Family':'👨‍👩‍👧‍👦','School':'🏫','Toys':'🧸','Feelings':'😊',
  'Weather':'☀️','Places':'📍','Actions':'🏃',
  'Adjectives':'✨','Jobs':'👷','Prepositions':'🧭','Questions':'❓'
};

// ===== 本地图片路径生成函数 =====
// v2 sits one folder below the shared image library, so reuse ../images.
// 失败/缺失时 renderOptions() 的 onerror 会自动回退到 emoji
function aiImg(word) {
  var slug = word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return 'images/' + slug + '.jpg';
}
// ===== 词库数据（实物类有AI图片，抽象类保持emoji）=====
var WORDS_DB = {
  "Animals": [
    {w:"cat",e:"🐱",i:aiImg("cat")},{w:"dog",e:"🐶",i:aiImg("dog")},{w:"tiger",e:"🐯",i:aiImg("tiger")},{w:"lion",e:"🦁",i:aiImg("lion")},
    {w:"elephant",e:"🐘",i:aiImg("elephant")},{w:"giraffe",e:"🦒",i:aiImg("giraffe")},{w:"zebra",e:"🦓",i:aiImg("zebra")},
    {w:"monkey",e:"🐵",i:aiImg("monkey")},{w:"panda",e:"🐼",i:aiImg("panda")},{w:"koala",e:"🐨",i:aiImg("koala")},
    {w:"kangaroo",e:"🦘",i:aiImg("kangaroo")},{w:"rabbit",e:"🐰",i:aiImg("rabbit")},{w:"hamster",e:"🐹",i:aiImg("hamster")},
    {w:"mouse",e:"🐭",i:aiImg("mouse")},{w:"bear",e:"🐻",i:aiImg("bear")},{w:"fox",e:"🦊",i:aiImg("fox")},
    {w:"wolf",e:"🐺",i:aiImg("wolf")},{w:"pig",e:"🐷",i:aiImg("pig")},{w:"cow",e:"🐮",i:aiImg("cow")},
    {w:"horse",e:"🐴",i:aiImg("horse")},{w:"sheep",e:"🐑",i:aiImg("sheep")},{w:"goat",e:"🐐",i:aiImg("goat")},
    {w:"deer",e:"🦌",i:aiImg("deer")},{w:"chicken",e:"🐔",i:aiImg("chicken")},{w:"duck",e:"🦆",i:aiImg("duck")},
    {w:"bird",e:"🐦",i:aiImg("bird")},{w:"owl",e:"🦉",i:aiImg("owl")},{w:"penguin",e:"🐧",i:aiImg("penguin")},
    {w:"parrot",e:"🦜",i:aiImg("parrot")},{w:"peacock",e:"🦚",i:aiImg("peacock")},{w:"flamingo",e:"🦩",i:aiImg("flamingo")},
    {w:"swan",e:"🦢",i:aiImg("swan")},{w:"fish",e:"🐟",i:aiImg("fish")},{w:"dolphin",e:"🐬",i:aiImg("dolphin")},
    {w:"whale",e:"🐋",i:aiImg("whale")},{w:"shark",e:"🦈",i:aiImg("shark")},{w:"octopus",e:"🐙",i:aiImg("octopus")},
    {w:"crab",e:"🦀",i:aiImg("crab")},{w:"lobster",e:"🦞",i:aiImg("lobster")},{w:"shrimp",e:"🦐",i:aiImg("shrimp")},
    {w:"turtle",e:"🐢",i:aiImg("turtle")},{w:"snake",e:"🐍",i:aiImg("snake")},{w:"lizard",e:"🦎",i:aiImg("lizard")},
    {w:"frog",e:"🐸",i:aiImg("frog")},{w:"crocodile",e:"🐊",i:aiImg("crocodile")},{w:"hippo",e:"🦛",i:aiImg("hippopotamus")},
    {w:"rhino",e:"🦏",i:aiImg("rhinoceros")},{w:"camel",e:"🐫",i:aiImg("camel")},{w:"llama",e:"🦙",i:aiImg("llama")},
    {w:"bat",e:"🦇",i:aiImg("bat")},{w:"bee",e:"🐝",i:aiImg("bee")},{w:"butterfly",e:"🦋",i:aiImg("butterfly")},
    {w:"ladybug",e:"🐞",i:aiImg("ladybug")},{w:"snail",e:"🐌",i:aiImg("snail")},{w:"worm",e:"🪱",i:aiImg("worm")},
    {w:"ant",e:"🐜",i:aiImg("ant")},{w:"spider",e:"🕷️",i:aiImg("spider")},{w:"eagle",e:"🦅",i:aiImg("eagle")},
    {w:"seal",e:"🦭",i:aiImg("seal")},{w:"walrus",e:"🦪",i:aiImg("walrus")},{w:"mosquito",e:"🦟",i:aiImg("mosquito")},
    {w:"dragonfly",e:"🪰",i:aiImg("dragonfly")},{w:"grasshopper",e:"🦗",i:aiImg("grasshopper")},{w:"squirrel",e:"🐿️",i:aiImg("squirrel")},
    {w:"hedgehog",e:"🦔",i:aiImg("hedgehog")},{w:"otter",e:"🦦",i:aiImg("otter")},{w:"buffalo",e:"🐃",i:aiImg("buffalo")},
    {w:"donkey",e:"🫏",i:aiImg("donkey")},{w:"gorilla",e:"🦍",i:aiImg("gorilla")}
  ],
  "Vehicles": [
    {w:"car",e:"🚗",i:aiImg("car")},{w:"bus",e:"🚌",i:aiImg("bus")},{w:"truck",e:"🚚",i:aiImg("truck")},
    {w:"taxi",e:"🚕",i:aiImg("taxi")},{w:"ambulance",e:"🚑",i:aiImg("ambulance")},{w:"fire truck",e:"🚒",i:aiImg("fire truck")},
    {w:"police car",e:"🚓",i:aiImg("police car")},{w:"motorcycle",e:"🏍️",i:aiImg("motorcycle")},{w:"bicycle",e:"🚲",i:aiImg("bicycle")},
    {w:"scooter",e:"🛵",i:aiImg("scooter")},{w:"skateboard",e:"🛹",i:aiImg("skateboard")},{w:"train",e:"🚂",i:aiImg("train")},
    {w:"subway",e:"🚇",i:aiImg("subway train")},{w:"airplane",e:"✈️",i:aiImg("airplane")},{w:"helicopter",e:"🚁",i:aiImg("helicopter")},
    {w:"rocket",e:"🚀",i:aiImg("rocket")},{w:"boat",e:"🚤",i:aiImg("boat")},{w:"ship",e:"🚢",i:aiImg("ship")},
    {w:"sailboat",e:"⛵",i:aiImg("sailboat")},{w:"tractor",e:"🚜",i:aiImg("tractor")},{w:"van",e:"🚐",i:aiImg("van")},
    {w:"jeep",e:"🚙",i:aiImg("jeep")},{w:"school bus",e:"🚎",i:aiImg("school bus")},{w:"tank",e:"🪖",i:aiImg("military tank")},
    {w:"hot air balloon",e:"🎈",i:aiImg("hot air balloon")},{w:"parachute",e:"🪂",i:aiImg("parachute")},
    {w:"ferry",e:"⛴️",i:aiImg("ferry boat")},{w:"lifeboat",e:"🚣",i:aiImg("lifeboat")},{w:"canoe",e:"🛶",i:aiImg("canoe")},
    {w:"yacht",e:"🛥️",i:aiImg("yacht")},{w:"cart",e:"🛒",i:aiImg("shopping cart")},{w:"wheelchair",e:"♿",i:aiImg("wheelchair")},
    {w:"roller skates",e:"⛸️",i:aiImg("roller skates")},{w:"spaceship",e:"🛸",i:aiImg("spaceship")}
  ],
  "Furniture": [
    {w:"table",e:"🪑",i:aiImg("table")},{w:"chair",e:"🪑",i:aiImg("chair")},{w:"sofa",e:"🛋️",i:aiImg("sofa")},
    {w:"bed",e:"🛏️",i:aiImg("bed")},{w:"desk",e:"🪑",i:aiImg("desk")},{w:"bookshelf",e:"📚",i:aiImg("bookshelf")},
    {w:"closet",e:"🚪",i:aiImg("closet")},{w:"drawer",e:"🗄️",i:aiImg("drawer")},{w:"wardrobe",e:"🚪",i:aiImg("wardrobe")},
    {w:"shelf",e:"📚",i:aiImg("shelf")},{w:"lamp",e:"💡",i:aiImg("lamp")},{w:"carpet",e:"🟫",i:aiImg("carpet")},
    {w:"curtain",e:"🪟",i:aiImg("curtain")},{w:"mirror",e:"🪞",i:aiImg("mirror")},{w:"clock",e:"🕐",i:aiImg("wall clock")},
    {w:"pillow",e:"🛋️",i:aiImg("pillow")},{w:"blanket",e:"🛏️",i:aiImg("blanket")},{w:"rug",e:"🟫",i:aiImg("rug")},
    {w:"cushion",e:"🛋️",i:aiImg("cushion")},{w:"stool",e:"🪑",i:aiImg("stool")},{w:"bench",e:"🪑",i:aiImg("bench")},
    {w:"crib",e:"🛏️",i:aiImg("baby crib")},{w:"nightstand",e:"🪑",i:aiImg("nightstand")},{w:"dresser",e:"🗄️",i:aiImg("dresser")},
    {w:"cabinet",e:"🗄️",i:aiImg("cabinet")},{w:"armchair",e:"🛋️",i:aiImg("armchair")},{w:"sofa bed",e:"🛋️",i:aiImg("sofa bed")},
    {w:"fan",e:"🌀",i:aiImg("electric fan")},{w:"heater",e:"🔥",i:aiImg("heater")},{w:"tv stand",e:"📺",i:aiImg("TV stand")},
    {w:"trash can",e:"🗑️",i:aiImg("trash can")},{w:"iron",e:"👔",i:aiImg("clothing iron")}
  ],
  "Food": [
    {w:"apple",e:"🍎",i:aiImg("apple")},{w:"banana",e:"🍌",i:aiImg("banana")},{w:"orange",e:"🍊",i:aiImg("orange fruit")},
    {w:"grape",e:"🍇",i:aiImg("grapes")},{w:"strawberry",e:"🍓",i:aiImg("strawberry")},{w:"watermelon",e:"🍉",i:aiImg("watermelon")},
    {w:"pineapple",e:"🍍",i:aiImg("pineapple")},{w:"mango",e:"🥭",i:aiImg("mango")},{w:"peach",e:"🍑",i:aiImg("peach")},
    {w:"cherry",e:"🍒",i:aiImg("cherry")},{w:"pear",e:"🍐",i:aiImg("pear")},{w:"lemon",e:"🍋",i:aiImg("lemon")},
    {w:"bread",e:"🍞",i:aiImg("bread")},{w:"cheese",e:"🧀",i:aiImg("cheese")},{w:"egg",e:"🥚",i:aiImg("egg")},
    {w:"milk",e:"🥛",i:aiImg("glass of milk")},{w:"juice",e:"🧃",i:aiImg("fruit juice")},{w:"water",e:"💧",i:aiImg("glass of water")},
    {w:"cake",e:"🎂",i:aiImg("birthday cake")},{w:"cookie",e:"🍪",i:aiImg("cookie")},{w:"ice cream",e:"🍨",i:aiImg("ice cream")},
    {w:"candy",e:"🍬",i:aiImg("candy")},{w:"chocolate",e:"🍫",i:aiImg("chocolate bar")},{w:"pizza",e:"🍕",i:aiImg("pizza")},
    {w:"hamburger",e:"🍔",i:aiImg("hamburger")},{w:"hot dog",e:"🌭",i:aiImg("hot dog")},{w:"sandwich",e:"🥪",i:aiImg("sandwich")},
    {w:"soup",e:"🍲",i:aiImg("soup")},{w:"salad",e:"🥗",i:aiImg("salad")},{w:"rice",e:"🍚",i:aiImg("bowl of rice")},
    {w:"noodle",e:"🍜",i:aiImg("noodles")},{w:"donut",e:"🍩",i:aiImg("donut")},{w:"pancake",e:"🥞",i:aiImg("pancake")},
    {w:"popcorn",e:"🍿",i:aiImg("popcorn")},{w:"french fries",e:"🍟",i:aiImg("french fries")},
    {w:"tomato",e:"🍅",i:aiImg("tomato")},{w:"potato",e:"🥔",i:aiImg("potato")},{w:"onion",e:"🧅",i:aiImg("onion")},
    {w:"carrot",e:"🥕",i:aiImg("carrot")},{w:"corn",e:"🌽",i:aiImg("corn on cob")},{w:"cabbage",e:"🥬",i:aiImg("cabbage")},
    {w:"broccoli",e:"🥦",i:aiImg("broccoli")},{w:"eggplant",e:"🍆",i:aiImg("eggplant")},{w:"pepper",e:"🌶️",i:aiImg("bell pepper")},
    {w:"coconut",e:"🥥",i:aiImg("coconut")},{w:"avocado",e:"🥑",i:aiImg("avocado")},{w:"blueberry",e:"🫐",i:aiImg("blueberries")},
    {w:"kiwi",e:"🥝",i:aiImg("kiwi fruit")},{w:"plum",e:"🍑",i:aiImg("plum")},{w:"apricot",e:"🍑",i:aiImg("apricot")},
    {w:"fig",e:"🫒",i:aiImg("fig fruit")},{w:"toast",e:"🍞",i:aiImg("toast bread")},{w:"jam",e:"🍯",i:aiImg("jam jar")},
    {w:"honey",e:"🍯",i:aiImg("honey jar")},{w:"butter",e:"🧈",i:aiImg("butter")},{w:"sugar",e:"🍬",i:aiImg("sugar cubes")},
    {w:"salt",e:"🧂",i:aiImg("salt shaker")},{w:"tea",e:"🍵",i:aiImg("cup of tea")},{w:"coffee",e:"☕",i:aiImg("cup of coffee")},
    {w:"yogurt",e:"🥛",i:aiImg("yogurt cup")},{w:"steak",e:"🥩",i:aiImg("steak")},{w:"chicken meat",e:"🍗",i:aiImg("fried chicken")},
    {w:"bacon",e:"🥓",i:aiImg("bacon")},{w:"sausage",e:"🌭",i:aiImg("sausage")}
  ],
  "Colors": [
    {w:"red",e:"🔴"},{w:"blue",e:"🔵"},{w:"yellow",e:"🟡"},
    {w:"green",e:"🟢"},{w:"orange",e:"🟠"},{w:"purple",e:"🟣"},
    {w:"pink",e:"🩷"},{w:"brown",e:"🟤"},{w:"black",e:"⚫"},
    {w:"white",e:"⚪"},{w:"gray",e:"⬜"},
    {w:"gold",e:"🏆"},{w:"silver",e:"🥈"},{w:"beige",e:"🟨"},
    {w:"cyan",e:"🔵"},{w:"magenta",e:"🟣"},{w:"lime",e:"🟢"}
  ],
  "Shapes": [
    {w:"circle",e:"⭕"},{w:"square",e:"⬜"},{w:"triangle",e:"🔺"},
    {w:"star",e:"⭐"},{w:"heart",e:"❤️"},{w:"diamond",e:"💎"},
    {w:"oval",e:"⭕"},{w:"rectangle",e:"▬"},
    {w:"cube",e:"🧊"},{w:"sphere",e:"⚽"},{w:"cone",e:"📐"},
    {w:"cylinder",e:"🥫"},{w:"pyramid",e:"🔺"},{w:"cross",e:"➕"},
    {w:"arrow",e:"➡️"},{w:"moon",e:"🌙"},{w:"wave",e:"🌊"}
  ],
  "Clothes": [
    {w:"shirt",e:"👕",i:aiImg("shirt")},{w:"t-shirt",e:"👕",i:aiImg("t-shirt")},{w:"pants",e:"👖",i:aiImg("pants")},
    {w:"shorts",e:"🩳",i:aiImg("shorts")},{w:"dress",e:"👗",i:aiImg("dress")},{w:"skirt",e:"👗",i:aiImg("skirt")},
    {w:"jacket",e:"🧥",i:aiImg("jacket")},{w:"coat",e:"🧥",i:aiImg("coat")},{w:"socks",e:"🧦",i:aiImg("socks")},
    {w:"shoes",e:"👟",i:aiImg("shoes")},{w:"boots",e:"👢",i:aiImg("boots")},{w:"hat",e:"🧢",i:aiImg("hat")},
    {w:"cap",e:"🧢",i:aiImg("baseball cap")},{w:"gloves",e:"🧤",i:aiImg("gloves")},{w:"scarf",e:"🧣",i:aiImg("scarf")},
    {w:"umbrella",e:"☂️",i:aiImg("umbrella")},{w:"swimsuit",e:"👙",i:aiImg("swimsuit")},{w:"pajamas",e:"🛌",i:aiImg("pajamas")},
    {w:"vest",e:"🦺",i:aiImg("vest")},{w:"belt",e:"👖",i:aiImg("belt")},
    {w:"tie",e:"👔",i:aiImg("neck tie")},{w:"suit",e:"🤵",i:aiImg("suit")},{w:"uniform",e:"👔",i:aiImg("uniform")},
    {w:"sunglasses",e:"🕶️",i:aiImg("sunglasses")},{w:"watch",e:"⌚",i:aiImg("wristwatch")},{w:"ring",e:"💍",i:aiImg("ring")},
    {w:"necklace",e:"📿",i:aiImg("necklace")},{w:"earrings",e:"💎",i:aiImg("earrings")},{w:"bracelet",e:"⌚",i:aiImg("bracelet")},
    {w:"wallet",e:"👛",i:aiImg("wallet")},{w:"purse",e:"👜",i:aiImg("purse")},{w:"backpack",e:"🎒",i:aiImg("backpack")},
    {w:"handbag",e:"👜",i:aiImg("handbag")},{w:"sandals",e:"👡",i:aiImg("sandals")},{w:"slippers",e:"🩴",i:aiImg("slippers")},
    {w:"raincoat",e:"🧥",i:aiImg("raincoat")},{w:"mittens",e:"🧤",i:aiImg("mittens")},{w:"apron",e:"👗",i:aiImg("apron")}
  ],
  "Home": [
    {w:"house",e:"🏠",i:aiImg("house")},{w:"door",e:"🚪",i:aiImg("door")},{w:"window",e:"🪟",i:aiImg("window")},
    {w:"wall",e:"🧱",i:aiImg("brick wall")},{w:"floor",e:"🟫",i:aiImg("wooden floor")},{w:"ceiling",e:"🏠",i:aiImg("ceiling")},
    {w:"roof",e:"🏠",i:aiImg("roof")},{w:"garden",e:"🌻",i:aiImg("garden")},{w:"garage",e:"🅿️",i:aiImg("garage")},
    {w:"kitchen",e:"🍳",i:aiImg("kitchen")},{w:"bedroom",e:"🛏️",i:aiImg("bedroom")},{w:"bathroom",e:"🚿",i:aiImg("bathroom")},
    {w:"living room",e:"🛋️",i:aiImg("living room")},{w:"stairs",e:"🪜",i:aiImg("stairs")},{w:"balcony",e:"🌸",i:aiImg("balcony")},
    {w:"key",e:"🔑",i:aiImg("key")},{w:"lock",e:"🔒",i:aiImg("lock")},{w:"bell",e:"🔔",i:aiImg("door bell")},
    {w:"fence",e:"🚧",i:aiImg("fence")},{w:"gate",e:"🚪",i:aiImg("gate")},{w:"mailbox",e:"📮",i:aiImg("mailbox")},
    {w:"fridge",e:"🧊",i:aiImg("refrigerator")},{w:"microwave",e:"📻",i:aiImg("microwave oven")},{w:"oven",e:"🔥",i:aiImg("oven")},
    {w:"stove",e:"🔥",i:aiImg("kitchen stove")},{w:"sink",e:"🚰",i:aiImg("kitchen sink")},{w:"faucet",e:"🚰",i:aiImg("faucet")},
    {w:"dishwasher",e:"🍽️",i:aiImg("dishwasher")},{w:"washing machine",e:"🧺",i:aiImg("washing machine")},
    {w:"vacuum",e:"🧹",i:aiImg("vacuum cleaner")},{w:"broom",e:"🧹",i:aiImg("broom")},{w:"bucket",e:"🪣",i:aiImg("bucket")},
    {w:"rope",e:"🪢",i:aiImg("rope")},{w:"ladder",e:"🪜",i:aiImg("ladder")},{w:"hammer",e:"🔨",i:aiImg("hammer")},
    {w:"nail",e:"🔩",i:aiImg("nail")},{w:"screwdriver",e:"🪛",i:aiImg("screwdriver")},{w:"tape",e:"🎞️",i:aiImg("scotch tape")},
    {w:"glue",e:"🧴",i:aiImg("glue bottle")},{w:"soap",e:"🧼",i:aiImg("soap bar")},{w:"towel",e:"🧻",i:aiImg("towel")},
    {w:"tissue",e:"🧻",i:aiImg("tissue box")},{w:"toilet paper",e:"🧻",i:aiImg("toilet paper")},{w:"shampoo",e:"🧴",i:aiImg("shampoo bottle")}
  ],
  "Nature": [
    {w:"tree",e:"🌳",i:aiImg("tree")},{w:"flower",e:"🌸",i:aiImg("beautiful flower")},{w:"grass",e:"🌿",i:aiImg("green grass")},
    {w:"leaf",e:"🍃",i:aiImg("leaf")},{w:"sun",e:"☀️",i:aiImg("bright sun")},{w:"moon",e:"🌙",i:aiImg("full moon")},
    {w:"star",e:"⭐",i:aiImg("star in night sky")},{w:"cloud",e:"☁️",i:aiImg("clouds")},{w:"rain",e:"🌧️",i:aiImg("rain falling")},
    {w:"snow",e:"❄️",i:aiImg("snow falling")},{w:"wind",e:"💨",i:aiImg("wind blowing leaves")},{w:"rainbow",e:"🌈",i:aiImg("rainbow")},
    {w:"mountain",e:"⛰️",i:aiImg("mountain peak")},{w:"river",e:"🌊",i:aiImg("river")},{w:"ocean",e:"🌊",i:aiImg("ocean waves")},
    {w:"beach",e:"🏖️",i:aiImg("sandy beach")},{w:"island",e:"🏝️",i:aiImg("tropical island")},{w:"forest",e:"🌲",i:aiImg("forest trees")},
    {w:"desert",e:"🏜️",i:aiImg("desert sand dunes")},{w:"volcano",e:"🌋",i:aiImg("volcano erupting")},{w:"stone",e:"🪨",i:aiImg("stone rock")},
    {w:"mushroom",e:"🍄",i:aiImg("mushroom")},{w:"cactus",e:"🌵",i:aiImg("cactus plant")},
    {w:"lake",e:"🏞️",i:aiImg("lake")},{w:"waterfall",e:"💧",i:aiImg("waterfall")},{w:"valley",e:"🏞️",i:aiImg("green valley")},
    {w:"hill",e:"⛰️",i:aiImg("grassy hill")},{w:"cliff",e:"🪨",i:aiImg("rocky cliff")},{w:"cave",e:"🕳️",i:aiImg("cave entrance")},
    {w:"pond",e:"🌊",i:aiImg("pond with ducks")},{w:"spring",e:"💧",i:aiImg("natural spring water")},{w:"seed",e:"🌱",i:aiImg("seeds")},
    {w:"root",e:"🌳",i:aiImg("plant roots")},{w:"branch",e:"🌳",i:aiImg("tree branch")},{w:"trunk",e:"🪵",i:aiImg("tree trunk")},
    {w:"bark",e:"🪵",i:aiImg("tree bark")},{w:"petal",e:"🌸",i:aiImg("flower petal")},{w:"bud",e:"🌱",i:aiImg("flower bud")},
    {w:"dew",e:"💧",i:aiImg("dew drops on grass")},{w:"frost",e:"❄️",i:aiImg("frost on window")},{w:"mist",e:"🌫️",i:aiImg("morning mist")}
  ],
  "Body": [
    {w:"head",e:"👤"},{w:"face",e:"😊"},{w:"eye",e:"👁️"},
    {w:"ear",e:"👂"},{w:"nose",e:"👃"},{w:"mouth",e:"👄"},
    {w:"tooth",e:"🦷"},{w:"tongue",e:"👅"},{w:"hair",e:"💇"},
    {w:"hand",e:"✋"},{w:"arm",e:"💪"},{w:"leg",e:"🦵"},
    {w:"foot",e:"🦶"},{w:"knee",e:"🦵"},{w:"elbow",e:"💪"},
    {w:"finger",e:"👆"},{w:"thumb",e:"👍"},{w:"belly",e:"🤰"},
    {w:"back",e:"🔙"},{w:"shoulder",e:"💪"},
    {w:"neck",e:"🧣"},{w:"cheek",e:"😊"},{w:"chin",e:"😊"},
    {w:"forehead",e:"👤"},{w:"eyebrow",e:"👁️"},{w:"eyelash",e:"👁️"},
    {w:"gum",e:"🦷"},{w:"lip",e:"👄"},{w:"skin",e:"✋"},
    {w:"bone",e:"🦴"},{w:"muscle",e:"💪"},{w:"blood",e:"🩸"},
    {w:"heart organ",e:"❤️"},{w:"stomach",e:"🤰"},{w:"brain",e:"🧠"}
  ],
  "Numbers": [
    {w:"one",e:"1"},{w:"two",e:"2"},{w:"three",e:"3"},
    {w:"four",e:"4"},{w:"five",e:"5"},{w:"six",e:"6"},
    {w:"seven",e:"7"},{w:"eight",e:"8"},{w:"nine",e:"9"},
    {w:"ten",e:"10"},{w:"eleven",e:"11"},{w:"twelve",e:"12"},
    {w:"thirteen",e:"13"},{w:"fourteen",e:"14"},{w:"fifteen",e:"15"},
    {w:"sixteen",e:"16"},{w:"seventeen",e:"17"},{w:"eighteen",e:"18"},
    {w:"nineteen",e:"19"},{w:"twenty",e:"20"},
    {w:"thirty",e:"30"},{w:"forty",e:"40"},{w:"fifty",e:"50"},
    {w:"sixty",e:"60"},{w:"seventy",e:"70"},{w:"eighty",e:"80"},
    {w:"ninety",e:"90"},{w:"hundred",e:"💯"},
    {w:"first",e:"🥇"},{w:"second",e:"🥈"},{w:"third",e:"🥉"},
    {w:"half",e:"½"},{w:"quarter",e:"¼"}
  ],
  "Time": [
    {w:"morning",e:"🌅"},{w:"noon",e:"☀️"},{w:"afternoon",e:"🌤️"},
    {w:"evening",e:"🌆"},{w:"night",e:"🌙"},{w:"today",e:"📅"},
    {w:"tomorrow",e:"📆"},{w:"yesterday",e:"📅"},
    {w:"Monday",e:"📅"},{w:"Tuesday",e:"📅"},{w:"Wednesday",e:"📅"},
    {w:"Thursday",e:"📅"},{w:"Friday",e:"📅"},{w:"Saturday",e:"📅"},
    {w:"Sunday",e:"📅"},{w:"clock",e:"🕐"},{w:"hour",e:"🕐"},
    {w:"minute",e:"⏱️"},{w:"second",e:"⏱️"},{w:"week",e:"📅"},
    {w:"month",e:"📆"},{w:"year",e:"📅"},
    {w:"January",e:"📅"},{w:"February",e:"📅"},{w:"March",e:"🌸"},
    {w:"April",e:"🌷"},{w:"May",e:"🌻"},{w:"June",e:"☀️"},
    {w:"July",e:"🌻"},{w:"August",e:"🌻"},{w:"September",e:"🍂"},
    {w:"October",e:"🎃"},{w:"November",e:"🍂"},{w:"December",e:"❄️"},
    {w:"spring",e:"🌸"},{w:"summer",e:"☀️"},{w:"autumn",e:"🍂"},
    {w:"winter",e:"❄️"},{w:"season",e:"📅"},{w:"birthday",e:"🎂"},
    {w:"holiday",e:"🎉"},{w:"vacation",e:"✈️"},{w:"weekend",e:"📅"}
  ],
  "Family": [
    {w:"mom",e:"👩"},{w:"dad",e:"👨"},{w:"mother",e:"👩"},
    {w:"father",e:"👨"},{w:"sister",e:"👧"},{w:"brother",e:"👦"},
    {w:"grandma",e:"👵"},{w:"grandpa",e:"👴"},{w:"aunt",e:"👩"},
    {w:"uncle",e:"👨"},{w:"cousin",e:"👶"},{w:"baby",e:"👶"},
    {w:"family",e:"👨‍👩‍👧‍👦"},
    {w:"daughter",e:"👧"},{w:"son",e:"👦"},
    {w:"grandmother",e:"👵"},{w:"grandfather",e:"👴"},
    {w:"niece",e:"👧"},{w:"nephew",e:"👦"},
    {w:"twin",e:"👯"},{w:"friend",e:"🤝"},{w:"neighbor",e:"🏠"},
    {w:"classmate",e:"👨‍🎓"},{w:"partner",e:"🤝"}
  ],
  "School": [
    {w:"school",e:"🏫",i:aiImg("school building")},{w:"teacher",e:"👩‍🏫",i:aiImg("teacher")},{w:"student",e:"👨‍🎓",i:aiImg("student")},
    {w:"book",e:"📖",i:aiImg("open book")},{w:"pencil",e:"✏️",i:aiImg("pencil")},{w:"pen",e:"🖊️",i:aiImg("pen")},
    {w:"eraser",e:"🧽",i:aiImg("eraser")},{w:"ruler",e:"📏",i:aiImg("ruler")},{w:"scissors",e:"✂️",i:aiImg("scissors")},
    {w:"paper",e:"📄",i:aiImg("paper")},{w:"blackboard",e:"📝",i:aiImg("blackboard with writing")},{w:"crayon",e:"🖍️",i:aiImg("colorful crayons")},
    {w:"glue",e:"🧴",i:aiImg("glue stick")},{w:"paintbrush",e:"🖌️",i:aiImg("paintbrush")},
    {w:"desk",e:"🪑",i:aiImg("school desk")},{w:"classroom",e:"🏫",i:aiImg("classroom")},{w:"homework",e:"📝",i:aiImg("homework paper")},
    {w:"test",e:"📝",i:aiImg("test paper")},{w:"exam",e:"📝",i:aiImg("exam paper")},{w:"grade",e:"📊",i:aiImg("report card grade A")},
    {w:"library",e:"📚",i:aiImg("library books shelves")},{w:"dictionary",e:"📖",i:aiImg("thick dictionary")},{w:"notebook",e:"📓",i:aiImg("notebook")},
    {w:"folder",e:"📁",i:aiImg("folder")},{w:"calculator",e:"🧮",i:aiImg("calculator")},{w:"globe",e:"🌍",i:aiImg("world globe")},
    {w:"map",e:"🗺️",i:aiImg("world map on wall")},{w:"stapler",e:"📎",i:aiImg("stapler")},{w:"clip",e:"📎",i:aiImg("paper clip")},
    {w:"highlighter",e:"🖍️",i:aiImg("highlighter marker pen")},{w:"compass",e:"🧭",i:aiImg("drawing compass math tool")},{w:"protractor",e:"📐",i:aiImg("protractor")}
  ],
  "Toys": [
    {w:"ball",e:"⚽",i:aiImg("colorful ball")},{w:"doll",e:"🧸",i:aiImg("doll")},{w:"toy",e:"🧸",i:aiImg("children toys")},
    {w:"puzzle",e:"🧩",i:aiImg("jigsaw puzzle")},{w:"kite",e:"🪁",i:aiImg("kite flying in sky")},{w:"balloon",e:"🎈",i:aiImg("balloons")},
    {w:"drum",e:"🥁",i:aiImg("drum")},{w:"guitar",e:"🎸",i:aiImg("guitar")},{w:"piano",e:"🎹",i:aiImg("piano keyboard")},
    {w:"violin",e:"🎻",i:aiImg("violin")},{w:"trumpet",e:"🎺",i:aiImg("trumpet")},{w:"microphone",e:"🎤",i:aiImg("microphone")},
    {w:"camera",e:"📷",i:aiImg("camera")},{w:"telescope",e:"🔭",i:aiImg("telescope")},{w:"slide",e:"🛝",i:aiImg("playground slide")},
    {w:"swing",e:"🛝",i:aiImg("playground swing")},{w:"sandbox",e:"🏖️",i:aiImg("sandbox with sand")},
    {w:"teddy bear",e:"🧸",i:aiImg("teddy bear plush toy")},{w:"toy car",e:"🚗",i:aiImg("toy car for kids")},{w:"robot",e:"🤖",i:aiImg("cute robot toy")},
    {w:"blocks",e:"🧱",i:aiImg("building blocks toy")},{w:"lego",e:"🧱",i:aiImg("lego bricks colorful")},{w:"yo-yo",e:"🪀",i:aiImg("yoyo toy")},
    {w:"marbles",e:"⚪",i:aiImg("colorful glass marbles")},{w:"jump rope",e:"🪢",i:aiImg("jump rope")},{w:"hula hoop",e:"⭕",i:aiImg("hula hoop toy")},
    {w:"remote control",e:"📱",i:aiImg("TV remote control")},{w:"video game",e:"🎮",i:aiImg("video game controller")}
  ],
  "Feelings": [
    {w:"happy",e:"😊"},{w:"sad",e:"😢"},{w:"angry",e:"😠"},
    {w:"scared",e:"😨"},{w:"surprised",e:"😮"},{w:"tired",e:"😴"},
    {w:"hungry",e:"😋"},{w:"thirsty",e:"🤤"},{w:"sick",e:"🤒"},
    {w:"sleepy",e:"😴"},{w:"excited",e:"🤩"},{w:"brave",e:"💪"},
    {w:"proud",e:"😤"},{w:"shy",e:"😳"},{w:"worried",e:"😟"},
    {w:"lonely",e:"😢"},{w:"bored",e:"😐"},{w:"confused",e:"😕"},
    {w:"calm",e:"😌"},{w:"nervous",e:"😰"},{w:"relaxed",e:"😌"},
    {w:"love",e:"❤️"},{w:"hate",e:"😠"},{w:"hopeful",e:"🤞"}
  ],
  "Weather": [
    {w:"sunny",e:"☀️"},{w:"cloudy",e:"☁️"},{w:"rainy",e:"🌧️"},
    {w:"snowy",e:"❄️"},{w:"windy",e:"💨"},{w:"stormy",e:"⛈️"},
    {w:"foggy",e:"🌫️"},{w:"warm",e:"🌡️"},{w:"cool",e:"❄️"},
    {w:"cold",e:"🥶"},{w:"hot",e:"🥵"},{w:"humid",e:"💦"},
    {w:"dry",e:"🏜️"},{w:"wet",e:"💧"},{w:"freezing",e:"🧊"},
    {w:"boiling",e:"🔥"},{w:"temperature",e:"🌡️"}
  ],
  "Places": [
    {w:"park",e:"🌳",i:aiImg("beautiful park")},{w:"zoo",e:"🦁",i:aiImg("zoo with animals")},{w:"library",e:"📚",i:aiImg("public library building")},
    {w:"hospital",e:"🏥",i:aiImg("hospital building")},{w:"store",e:"🏪",i:aiImg("convenience store")},{w:"restaurant",e:"🍽️",i:aiImg("restaurant interior")},
    {w:"farm",e:"🌾",i:aiImg("farm with barn and animals")},{w:"airport",e:"✈️",i:aiImg("airport terminal")},{w:"station",e:"🚉",i:aiImg("train station")},
    {w:"bank",e:"🏦",i:aiImg("bank building")},{w:"post office",e:"📮",i:aiImg("post office building")},{w:"cinema",e:"🎬",i:aiImg("movie cinema theater")},
    {w:"museum",e:"🏛️",i:aiImg("museum building")},{w:"church",e:"⛪",i:aiImg("church building")},{w:"temple",e:"🛕",i:aiImg("temple building")},
    {w:"supermarket",e:"🛒",i:aiImg("supermarket aisle")},{w:"bakery",e:"🍞",i:aiImg("bakery shop with breads")},{w:"pharmacy",e:"💊",i:aiImg("pharmacy drug store")},
    {w:"hotel",e:"🏨",i:aiImg("hotel building")},{w:"pool",e:"🏊",i:aiImg("swimming pool")},{w:"gym",e:"🏋️",i:aiImg("gym fitness center")},
    {w:"playground",e:"🛝",i:aiImg("children playground")},{w:"beach",e:"🏖️",i:aiImg("beach with palm trees")},{w:"campsite",e:"🏕️",i:aiImg("camping tent in nature")},
    {w:"city",e:"🏙️",i:aiImg("modern city skyline")},{w:"village",e:"🏘️",i:aiImg("small village houses")},{w:"country",e:"🌍",i:aiImg("countryside green fields")},
    {w:"street",e:"🛣️",i:aiImg("city street")},{w:"bridge",e:"🌉",i:aiImg("bridge over water")},{w:"tower",e:"🏢",i:aiImg("tall tower skyscraper")},
    {w:"castle",e:"🏰",i:aiImg("medieval castle")},{w:"palace",e:"🏛️",i:aiImg("grand palace")},{w:"market",e:"🏪",i:aiImg("outdoor market with stalls")}
  ],
  "Actions": [
    {w:"hello",e:"👋"},{w:"goodbye",e:"👋"},{w:"please",e:"🙏"},
    {w:"thank you",e:"🙏"},{w:"sorry",e:"😔"},{w:"yes",e:"✅"},
    {w:"no",e:"❌"},{w:"help",e:"🆘"},{w:"stop",e:"🛑"},
    {w:"go",e:"🏃"},{w:"wait",e:"⏳"},{w:"look",e:"👀"},
    {w:"listen",e:"👂"},{w:"sit",e:"🪑"},{w:"stand",e:"🧍"},
    {w:"walk",e:"🚶"},{w:"run",e:"🏃"},{w:"jump",e:"🦘"},
    {w:"swim",e:"🏊"},{w:"dance",e:"💃"},{w:"sing",e:"🎤"},
    {w:"eat",e:"🍽️"},{w:"drink",e:"🥤"},{w:"play",e:"🎮"},
    {w:"read",e:"📖"},{w:"write",e:"✍️"},{w:"draw",e:"🎨"},
    {w:"sleep",e:"😴"},{w:"wake up",e:"☀️"},{w:"open",e:"🔓"},
    {w:"close",e:"🔒"},{w:"clean",e:"🧹"},{w:"wash",e:"🚿"},
    {w:"cook",e:"🍳"},{w:"smile",e:"😊"},{w:"laugh",e:"😂"},
    {w:"cry",e:"😢"},{w:"share",e:"🤝"},
    {w:"think",e:"🤔"},{w:"remember",e:"🧠"},{w:"forget",e:"🤔"},
    {w:"understand",e:"💡"},{w:"learn",e:"📖"},{w:"teach",e:"👩‍🏫"},
    {w:"study",e:"📚"},{w:"practice",e:"🏋️"},{w:"count",e:"🔢"},
    {w:"measure",e:"📏"},{w:"build",e:"🔨"},{w:"fix",e:"🔧"},
    {w:"break",e:"💔"},{w:"push",e:"👐"},{w:"pull",e:"🤏"},
    {w:"carry",e:"📦"},{w:"lift",e:"💪"},{w:"throw",e:"🤾"},
    {w:"catch",e:"🤲"},{w:"kick",e:"⚽"},{w:"hit",e:"👊"},
    {w:"clap",e:"👏"},{w:"point",e:"👆"},{w:"shake hands",e:"🤝"},
    {w:"wave",e:"👋"},{w:"nod",e:"🙆"},{w:"hug",e:"🤗"},
    {w:"kiss",e:"💋"},{w:"blink",e:"👁️"},{w:"breathe",e:"🌬️"},
    {w:"cough",e:"🤒"},{w:"sneeze",e:"🤧"},{w:"hiccup",e:"😅"},
    {w:"burp",e:"😅"},{w:"yawn",e:"😴"},{w:"stretch",e:"🤸"},
    {w:"climb",e:"🧗"},{w:"crawl",e:"🐛"},{w:"slide",e:"🛝"},
    {w:"fall",e:"🤕"},{w:"fly",e:"🕊️"},{w:"row",e:"🚣"},
    {w:"drive",e:"🚗"},{w:"ride",e:"🚲"},{w:"turn",e:"↩️"},
    {w:"pick up",e:"🤏"},{w:"put down",e:"📥"},{w:"hang",e:"🪝"},
    {w:"tie",e:"🎀"},{w:"cut",e:"✂️"},{w:"paste",e:"📋"},
    {w:"type",e:"⌨️"},{w:"click",e:"🖱️"},{w:"print",e:"🖨️"},
    {w:"copy",e:"📋"},{w:"search",e:"🔍"},{w:"find",e:"🔍"},
    {w:"lose",e:"😢"},{w:"win",e:"🏆"},{w:"tie game",e:"🤝"},
    {w:"arrive",e:"🏁"},{w:"leave",e:"🚪"},{w:"return",e:"🔙"},
    {w:"start",e:"▶️"},{w:"finish",e:"🏁"},{w:"continue",e:"▶️"}
  ],
  "Adjectives": [
    {w:"big",e:"📏"},{w:"small",e:"📏"},{w:"large",e:"📏"},
    {w:"little",e:"📏"},{w:"long",e:"📏"},{w:"short",e:"📏"},
    {w:"tall",e:"📏"},{w:"wide",e:"📏"},{w:"narrow",e:"📏"},
    {w:"thin",e:"📏"},{w:"thick",e:"📏"},{w:"fat",e:"📏"},
    {w:"heavy",e:"⚖️"},{w:"light",e:"⚖️"},{w:"fast",e:"⚡"},
    {w:"slow",e:"🐢"},{w:"hard",e:"🪨"},{w:"soft",e:"🧸"},
    {w:"hot",e:"🔥"},{w:"cold",e:"🧊"},{w:"warm",e:"🌡️"},
    {w:"cool",e:"❄️"},{w:"wet",e:"💧"},{w:"dry",e:"🏜️"},
    {w:"clean",e:"✨"},{w:"dirty",e:"🧹"},{w:"new",e:"🆕"},
    {w:"old",e:"👴"},{w:"young",e:"👶"},{w:"fresh",e:"🥬"},
    {w:"sweet",e:"🍬"},{w:"sour",e:"🍋"},{w:"salty",e:"🧂"},
    {w:"bitter",e:"☕"},{w:"spicy",e:"🌶️"},{w:"delicious",e:"😋"},
    {w:"beautiful",e:"🌺"},{w:"ugly",e:"👹"},{w:"cute",e:"🥰"},
    {w:"pretty",e:"🌸"},{w:"handsome",e:"🤵"},{w:"funny",e:"😂"},
    {w:"serious",e:"😐"},{w:"quiet",e:"🤫"},{w:"loud",e:"🔊"},
    {w:"strong",e:"💪"},{w:"weak",e:"🤕"},{w:"brave",e:"🦸"},
    {w:"kind",e:"💗"},{w:"mean",e:"😠"},{w:"nice",e:"🙂"},
    {w:"naughty",e:"😈"},{w:"polite",e:"🙇"},{w:"rude",e:"😤"},
    {w:"happy",e:"😊"},{w:"sad",e:"😢"},{w:"angry",e:"😠"},
    {w:"scared",e:"😨"},{w:"safe",e:"🛡️"},{w:"dangerous",e:"⚠️"},
    {w:"easy",e:"😄"},{w:"difficult",e:"🤯"},{w:"important",e:"⭐"},
    {w:"cheap",e:"💰"},{w:"expensive",e:"💎"},{w:"full",e:"🈵"},
    {w:"empty",e:"🈳"},{w:"busy",e:"🏃"},{w:"free",e:"🆓"},
    {w:"right",e:"✅"},{w:"wrong",e:"❌"},{w:"true",e:"✅"},
    {w:"false",e:"❌"},{w:"same",e:"🔄"},{w:"different",e:"🔄"}
  ],
  "Jobs": [
    {w:"doctor",e:"👨‍⚕️",i:aiImg("doctor in white coat")},{w:"nurse",e:"👩‍⚕️",i:aiImg("nurse uniform")},{w:"teacher",e:"👩‍🏫",i:aiImg("teacher at blackboard")},
    {w:"police officer",e:"👮",i:aiImg("police officer uniform")},{w:"firefighter",e:"👨‍🚒",i:aiImg("firefighter with helmet")},{w:"chef",e:"👨‍🍳",i:aiImg("chef cooking in kitchen")},
    {w:"farmer",e:"👨‍🌾",i:aiImg("farmer in field")},{w:"driver",e:"🚗",i:aiImg("bus driver")},{w:"pilot",e:"👨‍✈️",i:aiImg("airplane pilot in cockpit")},
    {w:"scientist",e:"👨‍🔬",i:aiImg("scientist in lab coat")},
    {w:"artist",e:"🎨",i:aiImg("artist painting on canvas")},{w:"musician",e:"🎵",i:aiImg("musician playing instrument")},{w:"dancer",e:"💃",i:aiImg("dancer performing ballet")},
    {w:"actor",e:"🎭",i:aiImg("actor on stage")},{w:"singer",e:"🎤",i:aiImg("singer performing on stage")},{w:"writer",e:"✍️",i:aiImg("writer typing on laptop")},
    {w:"engineer",e:"👷",i:aiImg("engineer with hard hat")},{w:"architect",e:"🏗️",i:aiImg("architect looking at blueprints")},{w:"lawyer",e:"⚖️",i:aiImg("lawyer in court")},
    {w:"judge",e:"⚖️",i:aiImg("judge with gavel")},{w:"soldier",e:"🪖",i:aiImg("soldier in military uniform")},{w:"vet",e:"🐾",i:aiImg("veterinarian with dog and cat")},
    {w:"dentist",e:"🦷",i:aiImg("dentist examining teeth")},{w:"baker",e:"🍞",i:aiImg("baker making bread")},{w:"barber",e:"💇",i:aiImg("barber cutting hair")},
    {w:"tailor",e:"🧵",i:aiImg("tailor sewing clothes")},{w:"photographer",e:"📷",i:aiImg("photographer with camera")},{w:"reporter",e:"📰",i:aiImg("news reporter journalist")},
    {w:"postman",e:"📮",i:aiImg("mail carrier postman delivering mail")},{w:"gardener",e:"🌻",i:aiImg("gardener planting flowers")},{w:"cleaner",e:"🧹",i:aiImg("janitor cleaning floor")},
    {w:"builder",e:"🔨",i:aiImg("construction worker builder")},{w:"plumber",e:"🔧",i:aiImg("plumber fixing pipes")},{w:"electrician",e:"💡",i:aiImg("electrician working on wires")},
    {w:"mechanic",e:"🔧",i:aiImg("car mechanic repairing engine")},{w:"fisherman",e:"🎣",i:aiImg("fisherman catching fish")},{w:"lifeguard",e:"🏊",i:aiImg("lifeguard at pool tower")}
  ],
  "Prepositions": [
    {w:"in",e:"📥"},{w:"on",e:"🔝"},{w:"at",e:"📍"},
    {w:"under",e:"⬇️"},{w:"over",e:"⬆️"},{w:"above",e:"⬆️"},
    {w:"below",e:"⬇️"},{w:"between",e:"↔️"},{w:"beside",e:"➡️"},
    {w:"next to",e:"➡️"},{w:"near",e:"📍"},{w:"far from",e:"📍"},
    {w:"behind",e:"🔙"},{w:"in front of",e:"🔜"},
    {w:"inside",e:"📥"},{w:"outside",e:"📤"},
    {w:"up",e:"⬆️"},{w:"down",e:"⬇️"},{w:"left",e:"⬅️"},
    {w:"right",e:"➡️"},{w:"across",e:"↔️"},{w:"through",e:"🔓"},
    {w:"around",e:"🔄"},{w:"into",e:"📥"},{w:"out of",e:"📤"},
    {w:"with",e:"🤝"},{w:"without",e:"🚫"},{w:"for",e:"🎁"},
    {w:"from",e:"🔙"},{w:"to",e:"🔜"},{w:"by",e:"🚌"}
  ],
  "Questions": [
    {w:"what",e:"❓"},{w:"who",e:"❓"},{w:"where",e:"📍"},
    {w:"when",e:"🕐"},{w:"why",e:"❓"},{w:"how",e:"❓"},
    {w:"which",e:"❓"},{w:"whose",e:"❓"},{w:"whom",e:"❓"},
    {w:"how many",e:"🔢"},{w:"how much",e:"💰"},{w:"how old",e:"🎂"},
    {w:"how long",e:"⏱️"},{w:"how often",e:"📅"},{w:"how far",e:"📍"},
    {w:"what time",e:"🕐"},{w:"what color",e:"🎨"},{w:"what kind",e:"❓"}
  ]
};

var CATEGORIES = Object.keys(WORDS_DB);
